import SortHeader from './SortHeader'
import { useModelSort } from './useModelSort'
import type { PCAReport } from './api'
import { getModelHistoryUrl } from './api'

export type HistoricalModel = PCAReport & { archived_at: string }
const pct = (value: number | null) => value === null ? '—' : `${(value * 100).toFixed(1)}%`
const num = (value: number) => value !== 0 && Math.abs(value) < .001 ? value.toExponential(3) : value.toLocaleString(undefined, { maximumFractionDigits: 3 })

export default function ModelHistory({ history, current, selected }: { history: HistoricalModel[]; current: PCAReport[]; selected: string }) {
  const unsorted = [...current.map((r) => ({ ...r, archived_at: '' })), ...history]
  const sorted = useModelSort(unsorted, 'performance', selected)
  return <section className="panel model-history"><div className="panel-heading"><h3>Results history · previous vs current runs</h3><span>{history.length} archived · {current.length} current</span></div>
    <p className="feature-note">Previous scores and parameters remain after fitted models are removed. Compare runs using the same test images; preprocessing versions may differ. The image columns follow the image selected above.</p>
    <div className="model-controls feature-note"><label>History ranking <select aria-label="History ranking" value={sorted.sort.key} onChange={(e) => sorted.setSort({ key: e.target.value, direction: 'desc' })}><option value="performance">Defect recall first, then fewer false alarms</option><option value="balanced">Balanced recall / good-plate specificity</option><option value="correct">Selected image: correct first</option><option value="archived">Newest / current first</option>{!['performance', 'balanced', 'correct', 'archived'].includes(sorted.sort.key) && <option value={sorted.sort.key}>Column: {sorted.sort.key}</option>}</select></label><span>Click any metric header to sort or reverse its order.</span></div>
    <div className="model-table-scroll"><table><thead><tr><SortHeader column="archived" sort={sorted.sort} onSort={sorted.choose}>Status / archived</SortHeader><SortHeader column="name" sort={sorted.sort} onSort={sorted.choose}>Model / ID</SortHeader><SortHeader column="parameters" sort={sorted.sort} onSort={sorted.choose}>Parameters</SortHeader><SortHeader column="features" sort={sorted.sort} onSort={sorted.choose}>Features / pipeline</SortHeader><SortHeader column="images" sort={sorted.sort} onSort={sorted.choose}>Images / skipped</SortHeader><SortHeader column="accuracy" sort={sorted.sort} onSort={sorted.choose}>Accuracy</SortHeader><SortHeader column="recall" sort={sorted.sort} onSort={sorted.choose}>Recall</SortHeader><SortHeader column="precision" sort={sorted.sort} onSort={sorted.choose}>Precision</SortHeader><SortHeader column="f1" sort={sorted.sort} onSort={sorted.choose}>F1</SortHeader><SortHeader column="fpr" sort={sorted.sort} onSort={sorted.choose}>False alarms</SortHeader><SortHeader column="tp" sort={sorted.sort} onSort={sorted.choose}>TP</SortHeader><SortHeader column="fp" sort={sorted.sort} onSort={sorted.choose}>FP</SortHeader><SortHeader column="tn" sort={sorted.sort} onSort={sorted.choose}>TN</SortHeader><SortHeader column="fn" sort={sorted.sort} onSort={sorted.choose}>FN</SortHeader><SortHeader column="correct" sort={sorted.sort} onSort={sorted.choose}>{selected || 'Selected image'} · correct first</SortHeader><SortHeader column="score" sort={sorted.sort} onSort={sorted.choose}>Image score</SortHeader><SortHeader column="threshold" sort={sorted.sort} onSort={sorted.choose}>Plate threshold</SortHeader><th>Record</th></tr></thead><tbody>{sorted.rows.map((r) => {
      const e = r.evaluation, image = e?.rows.find((row) => row.image_id === `metal_plate/test/${selected}`)
      return <tr key={`${r.archived_at}:${r.model_id}`}><td>{r.archived_at ? new Date(r.archived_at).toLocaleString() : 'Current'}</td><th>{r.name} · {r.model_id.slice(0, 8)}</th><td>{r.config.patch_size}px · {pct(r.config.variance_target)} · {r.config.model_type === 'one_class_svm' ? `${r.config.kernel}, nu ${r.config.nu}, gamma ${r.config.gamma}` : r.config.distance_metric ?? 'squared_l2'}</td><td>{r.config.feature_set ?? 'lab_sobel'} · {r.config.pipeline_signature?.slice(0, 8)}</td><td>{e ? `${e.images} / ${e.skipped.length}` : 'Not evaluated'}</td><td>{pct(e?.images ? (e.tp + e.tn) / e.images : null)}</td><td>{pct(e?.recall ?? null)}</td><td>{pct(e?.precision ?? null)}</td><td>{pct(e && 2 * e.tp + e.fp + e.fn ? 2 * e.tp / (2 * e.tp + e.fp + e.fn) : null)}</td><td>{pct(e?.false_positive_rate ?? null)}</td>{(['tp', 'fp', 'tn', 'fn'] as const).map((key) => <td key={key}>{e?.[key] ?? '—'}</td>)}<td className={image?.prediction === 'BAD' ? 'model-bad' : 'model-good'}>{image ? `${image.prediction} (actual ${image.actual})` : 'Not evaluated'}</td><td>{image ? num(image.score) : '—'}</td><td>{num(r.plate_threshold)}</td><td>{r.archived_at && <a href={getModelHistoryUrl(r.model_id)}>Results JSON</a>}</td></tr>
    })}</tbody></table></div>
    {!sorted.rows.length && <p className="empty">Results will appear here after training and replacement.</p>}
  </section>
}
