export default function Overview() {
  return <section className="overview">
    <div className="page-intro"><h2>Assignment Overview</h2></div>
    <details className="panel overview-content">
      <summary>Table of contents</summary>
      <ol className="contents-list">
        <li><a href="#dataset"><strong>Dataset viewer <span aria-hidden="true">→</span></strong><span>Browse folders, switch between grid and single images, and overlay ground truth.</span></a></li>
        <li><a href="#preprocessing"><strong>Preprocessing <span aria-hidden="true">→</span></strong><span>Explore training and test metal plates through normalization, thresholding, cleanup, and masking.</span></a></li>
        <li><a href="#features"><strong>Features <span aria-hidden="true">→</span></strong><span>Explore LAB and Sobel heatmaps and compare color distributions across good plates and defect types.</span></a></li>
        <li><a href="#models"><strong>Anomaly detection <span aria-hidden="true">→</span></strong><span>Train normal-only patch PCA, inspect feature CSVs, and evaluate anomaly scores on test plates.</span></a></li>
        <li><a href="#classifiers"><strong>Classifiers →</strong><span>Compare supervised PCA, SVM, and KNN on a mixed 80/20 split.</span></a></li>
        <li><a href="#cnn"><strong>CNN →</strong><span>Train ResNet-18 on segmented plates, compare class metrics, and inspect learned filters and predictions.</span></a></li>
        <li><a href="#comparison"><strong>Comparison and Business Use →</strong><span>Compare saved models on random images and rotations, including prediction time and costly missed defects.</span></a></li>
      </ol>
    </details>
    <article className="panel overview-content overview-summary">
      <h1>READ ME</h1>
      <p>The assignment was to use the MPDD dataset to tell whether a part was good or bad, with four days to explore the data, build a model, and try preprocessing and postprocessing. I could choose one of the allowed parts and use either supervised or unsupervised methods. I chose metal plates because they looked like a straightforward place to start, though the glare and light scratches made them harder than I expected.</p>
      <p>This webpage is my lab notebook for documenting the experiments and decisions I made for this problem. I built the client and server with AI assistance to help me inspect images, processing steps, and results. The focus of this submission is the CV work and the reasoning behind it. The app is the tool I used to make that work easier to inspect.</p>
      <p>The tabs follow the main stages of the project, although I went back and forth between preprocessing, features, and models. I try to explain in each tab why I had to go back to a previous step.</p>
      <h1>TLDR</h1>
      <p>This is a quick overview if you do not want to go through every tab. I used the metal plate dataset for this assignment. I made a preprocessing pipeline to segment out the plate and suppress glare. For the classical models, I then extracted LAB histograms, Sobel gradients, magnitude and direction, HOG, and Frangi features from local regions. I chose these to capture the texture and color differences between defects and the good blue paint. I hoped that combining color and edge information would help distinguish defects from glare, although these features can respond to glare too. I tested out a luminance normalization filter that moves luminance toward the intensity midpoint, making bright pixels darker and dark pixels brighter in an effort to fight the glare.</p>
      <p>I ran three types of models, anomaly detection, classifiers, and CNNs. The anomaly models learned from good plates using PCA reconstruction scores and one class SVMs. For supervised learning, the assignment allowed using defective images from the original test folder and making a new split. I combined the folders and used an 80/20 split for the classifiers and CNNs. I went beyond the good or bad decision and trained them to distinguish good plates, major rust, scratches, and total rust. The classical classifiers used PCA with a nearest centroid classifier, SVMs, and KNNs. I chose these because my initial thoughts were that I could solve this problem with some embedded space classification. I tried out CNNs with Resnet-18 architectures more as an experiment to see what features it learns, but they turned out to be strong contenders for a final model. I tried four CNN versions. The first used ResNet over the segmented plate. The second gave defect examples twice the weight in cross entropy loss. Both versions already used cross entropy, so the change was the class weighting. Then, I tried running it on regions of the plate to try to extract smaller details of scratches and differentiate between local and total rust. I ran a binary model predicting good from defect first as a test, then I ran a 4 class model to detect regions of defects.</p>
      <p>I ended up choosing the standard whole plate ResNet for this assignment. It did well on the supervised holdout and made predictions much faster than the patch models. I liked being able to see the regions and defect types from the four class patch CNN, but I did not need that extra detail just to decide whether a plate should pass inspection. The final tab looks at that tradeoff with timing and random rotations. I also explain where those comparisons include training images and what I would still want to test before using the model on new plates.</p>
    </article>
  </section>
}
